"""
Sauron internal dashboard — FastAPI app (port 8002)
"""
import asyncio
import json
import logging
import os
from contextlib import asynccontextmanager
from datetime import datetime, time as dtime, timedelta
from pathlib import Path
from typing import AsyncIterator

import httpx
import numpy as np
import polars as pl
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles

from gdpr_purge import run_purge as _run_gdpr_purge

logger = logging.getLogger(__name__)

INGEST_URL = os.getenv("INGEST_URL", "http://localhost:8010")

BASE    = Path(__file__).parent
DATA    = BASE / "data"
STATIC  = BASE / "static"

# ── Daily GDPR scheduler ─────────────────────────────────────────────────────
async def _gdpr_daily_scheduler() -> None:
    """Fires run_purge() every day at 02:00 local time."""
    while True:
        now    = datetime.now()
        target = datetime.combine(now.date(), dtime(2, 0))
        if now >= target:
            target = datetime.combine(now.date() + timedelta(days=1), dtime(2, 0))
        sleep_s = (target - now).total_seconds()
        logger.info("GDPR scheduler: next run in %.0fs (at %s)", sleep_s, target)
        await asyncio.sleep(sleep_s)
        try:
            result = _run_gdpr_purge()
            logger.info("GDPR daily purge done: %s", result)
            # Reload sauron_users so the API reflects new state
            global _sauron_users, _gdpr_log
            _sauron_users = pl.read_parquet(DATA / "sauron_users.parquet")
            _gdpr_log     = pl.read_parquet(DATA / "gdpr_log.parquet") if (DATA / "gdpr_log.parquet").exists() else pl.DataFrame()
        except Exception as exc:
            logger.exception("GDPR daily purge failed: %s", exc)

@asynccontextmanager
async def lifespan(app_: FastAPI):
    task = asyncio.create_task(_gdpr_daily_scheduler())
    yield
    task.cancel()

app = FastAPI(title="Sauron Dashboard", version="1.0.0", lifespan=lifespan)
app.mount("/static", StaticFiles(directory=str(STATIC)), name="static")

# ── lazy-loaded data ─────────────────────────────────────────────────────────
_clients       : pl.DataFrame | None = None
_credit_ledger : pl.DataFrame | None = None
_verifications : pl.DataFrame | None = None
_rings         : pl.DataFrame | None = None
_anomalies     : pl.DataFrame | None = None
_sauron_users  : pl.DataFrame | None = None
_gdpr_log      : pl.DataFrame | None = None

# Credit economy constants (must match build_data.py)
CREDIT_A_PER_KYC = 1.0    # 1 Credit A per full KYC
KYC_USD_PER_HEAD = 1.00   # $1/KYC break-even
CREDIT_B_USD     = 0.40   # USD per Credit B
EXCHANGE_A_TO_B  = 5.0    # 1 Credit A = 5 Credit B

# analytics (generated by compute_analytics.py)
_client_scores   : pl.DataFrame | None = None
_runway_forecast : pl.DataFrame | None = None
_anomalies_ml    : pl.DataFrame | None = None
_revenue_forecast: pl.DataFrame | None = None
_cohort_analysis : pl.DataFrame | None = None
_ring_curves     : pl.DataFrame | None = None
_elasticity      : pl.DataFrame | None = None
_load_forecast   : pl.DataFrame | None = None

def _load():
    global _clients, _credit_ledger, _verifications, _rings, _anomalies
    global _sauron_users, _gdpr_log
    if _clients is None:
        _clients       = pl.read_parquet(DATA / "clients.parquet")
        _credit_ledger = pl.read_parquet(DATA / "credit_ledger.parquet")
        _verifications = pl.read_parquet(DATA / "verifications.parquet")
        _rings         = pl.read_parquet(DATA / "ring_snapshots.parquet")
        _anomalies     = pl.read_parquet(DATA / "anomaly_events.parquet")
        _sauron_users  = pl.read_parquet(DATA / "sauron_users.parquet")
        _gdpr_log      = pl.read_parquet(DATA / "gdpr_log.parquet") if (DATA / "gdpr_log.parquet").exists() else pl.DataFrame()

def _load_analytics():
    global _client_scores, _runway_forecast, _anomalies_ml
    global _revenue_forecast, _cohort_analysis, _ring_curves
    global _elasticity, _load_forecast
    if _client_scores is None:
        _client_scores    = pl.read_parquet(DATA / "client_scores.parquet")
        _runway_forecast  = pl.read_parquet(DATA / "runway_forecast.parquet")
        _anomalies_ml     = pl.read_parquet(DATA / "anomalies_ml.parquet")
        _revenue_forecast = pl.read_parquet(DATA / "revenue_forecast.parquet")
        _cohort_analysis  = pl.read_parquet(DATA / "cohort_analysis.parquet")
        _ring_curves      = pl.read_parquet(DATA / "ring_curves.parquet")
        _elasticity       = pl.read_parquet(DATA / "elasticity.parquet")
        _load_forecast    = pl.read_parquet(DATA / "load_forecast.parquet")


# ── HTML pages ───────────────────────────────────────────────────────────────
def _page(name: str) -> HTMLResponse:
    f = STATIC / name
    if not f.exists():
        raise HTTPException(status_code=404, detail=f"{name} not found")
    return HTMLResponse(f.read_text())

@app.get("/",              response_class=HTMLResponse) 
def page_overview():       return _page("index.html")

@app.get("/tokens",        response_class=HTMLResponse)
def page_tokens():         return _page("credits.html")

@app.get("/verifications", response_class=HTMLResponse)
def page_verifications():  return _page("verifications.html")

@app.get("/rings",         response_class=HTMLResponse)
def page_rings():          return _page("rings.html")

@app.get("/clients",       response_class=HTMLResponse)
def page_clients():        return _page("clients.html")

@app.get("/anomalies",     response_class=HTMLResponse)
def page_anomalies():      return _page("anomalies.html")

@app.get("/insights",      response_class=HTMLResponse)
def page_insights():       return _page("insights.html")

@app.get("/gdpr",          response_class=HTMLResponse)
def page_gdpr():           return _page("gdpr.html")

@app.get("/pipeline",      response_class=HTMLResponse)
def page_pipeline():       return _page("pipeline.html")


# ── API: overview ─────────────────────────────────────────────────────────────
@app.get("/api/overview")
def api_overview():
    _load()

    total_verif = int(_verifications["total"].sum())
    total_full  = int(_verifications["full_kyc"].sum())
    total_red   = int(_verifications["reduced"].sum())
    total_fail  = int(_verifications["failed"].sum())

    # Unique registered users (personas who went through at least one KYC)
    unique_users = int(_sauron_users.height) if _sauron_users is not None else 0

    # KYC revenue: pass-through at $1/KYC
    kyc_revenue = round(total_full * KYC_USD_PER_HEAD, 2)

    # Query revenue: Credit B spent on attribute queries → USD
    total_b_spent = float(
        _credit_ledger.filter(pl.col("event_type") == "verify_spent")["amount"].abs().sum()
    )
    query_revenue = round(total_b_spent * CREDIT_B_USD, 2)

    # Credit A: minted vs converted → retained
    credit_a_minted = float(
        _credit_ledger.filter(
            (pl.col("credit_type") == "A") & (pl.col("amount") > 0)
        )["amount"].sum()
    )
    credit_a_converted = float(
        _credit_ledger.filter(pl.col("event_type") == "convert_to_B")["amount"].abs().sum()
    )
    credit_a_retained = round(credit_a_minted - credit_a_converted, 1)

    # Credit B: purchased + converted from A
    credit_b_purchased = float(
        _credit_ledger.filter(
            (pl.col("credit_type") == "B") & (pl.col("event_type") == "purchase")
        )["amount"].sum()
    )
    credit_b_converted = float(
        _credit_ledger.filter(pl.col("event_type") == "convert_from_A")["amount"].sum()
    )
    credit_b_face_value = round((credit_b_purchased + credit_b_converted) * CREDIT_B_USD, 2)

    # GDPR pending
    gdpr_pending = 0
    if _sauron_users is not None:
        from gdpr_purge import EU_EEA_COUNTRIES
        max_date = _verifications["date"].max() if _verifications.height > 0 else "2025-12-31"
        gdpr_pending = int(_sauron_users.filter(
            pl.col("country").is_in(list(EU_EEA_COUNTRIES)) &
            (pl.col("is_anonymized") == False)
        ).height)

    # Active client window: relative to max(date) in data
    max_date_str = _verifications["date"].max() if _verifications.height > 0 else "2025-12-31"
    from datetime import date as _date
    _max_d = _date.fromisoformat(max_date_str)
    _cutoff_90d = (_max_d - timedelta(days=90)).isoformat()
    _cutoff_chart = (_max_d - timedelta(days=90)).isoformat()

    active_clients = int(
        _verifications
        .filter(pl.col("date") >= _cutoff_90d)
        .select("client_id").unique().height
    )

    # daily Credit A earned and Credit B spent – last 90 days
    recent_a = (
        _credit_ledger
        .filter(
            (pl.col("date") >= _cutoff_chart) &
            (pl.col("credit_type") == "A") &
            (pl.col("event_type") == "kyc_earned")
        )
        .group_by("date")
        .agg(pl.sum("amount").alias("credit_a"))
        .sort("date")
    )
    recent_b = (
        _credit_ledger
        .filter(
            (pl.col("date") >= _cutoff_chart) &
            (pl.col("credit_type") == "B") &
            (pl.col("event_type") == "verify_spent")
        )
        .group_by("date")
        .agg(pl.sum("amount").alias("credit_b"))
        .sort("date")
    )
    recent = (
        recent_a.join(recent_b, on="date", how="outer_coalesce")
        .sort("date")
        .with_columns([
            pl.col("credit_a").fill_null(0.0),
            pl.col("credit_b").fill_null(0.0),
        ])
    )
    # ring sizes (latest snapshot)
    latest_ring = (
        _rings.sort("date")
        .group_by("ring_id")
        .agg(
            pl.last("ring_label").alias("label"),
            pl.last("member_count").alias("count"),
        )
        .sort("ring_id")
    )

    return {
        "kpis": {
            "total_verifications": total_verif,
            "total_full_kyc": total_full,
            "total_reduced": total_red,
            "total_failed": total_fail,
            "failure_rate": round(total_fail / max(total_verif, 1) * 100, 2),
            "active_clients": active_clients,
            "unique_registered_users": unique_users,
            "kyc_revenue_usd": kyc_revenue,
            "query_revenue_usd": query_revenue,
            "credit_a_total_minted": round(credit_a_minted, 0),
            "credit_a_retained": credit_a_retained,
            "credit_b_purchased": round(credit_b_purchased, 0),
            "credit_b_converted": round(credit_b_converted, 0),
            "credit_b_face_value": credit_b_face_value,
            "gdpr_pending": gdpr_pending,
        },
        "daily": {
            "dates":    recent["date"].to_list(),
            "credit_a": [round(v, 1) for v in recent["credit_a"].to_list()],
            "credit_b": [round(abs(v), 1) for v in recent["credit_b"].to_list()],
        },
        "rings": {
            "labels": latest_ring["ring_id"].to_list(),
            "names":  latest_ring["label"].to_list(),
            "counts": latest_ring["count"].to_list(),
        },
    }


# ── API: credits ───────────────────────────────────────────────────────────────
@app.get("/api/tokens")
def api_tokens():
    _load()

    # Max date in ledger for relative windows
    max_date_str = _credit_ledger["date"].max() if _credit_ledger.height > 0 else "2025-12-31"
    from datetime import date as _date
    _max_d = _date.fromisoformat(max_date_str)
    _cutoff_30d = (_max_d - timedelta(days=30)).isoformat()

    # Credit summary
    credit_a_minted = float(
        _credit_ledger.filter(
            (pl.col("credit_type") == "A") & (pl.col("amount") > 0)
        )["amount"].sum()
    )
    credit_a_converted = float(
        _credit_ledger.filter(pl.col("event_type") == "convert_to_B")["amount"].abs().sum()
    )
    credit_a_retained = round(credit_a_minted - credit_a_converted, 1)

    credit_b_converted = float(
        _credit_ledger.filter(pl.col("event_type") == "convert_from_A")["amount"].sum()
    )
    credit_b_face_value = round(credit_b_converted * CREDIT_B_USD, 2)

    # KYC revenue (pass-through)
    kyc_revenue = round(credit_a_minted * KYC_USD_PER_HEAD, 2)

    # Current balance per client and credit type
    last_bal = (
        _credit_ledger.sort("date")
        .group_by(["client_id","credit_type"])
        .agg(pl.last("balance_after").alias("balance"))
    )
    bal_a = {r["client_id"]: r["balance"] for r in last_bal.filter(pl.col("credit_type")=="A").iter_rows(named=True)}
    bal_b = {r["client_id"]: r["balance"] for r in last_bal.filter(pl.col("credit_type")=="B").iter_rows(named=True)}

    # 30-day Credit B burn
    spent_recent = (
        _credit_ledger
        .filter((pl.col("date") >= _cutoff_30d) & (pl.col("event_type") == "verify_spent"))
        .group_by("client_id")
        .agg(pl.col("amount").abs().sum().alias("b_spent_30d"))
    )
    spent_map = {r["client_id"]: r["b_spent_30d"] for r in spent_recent.iter_rows(named=True)}

    # 30-day Credit A earned
    earned_recent = (
        _credit_ledger
        .filter((pl.col("date") >= _cutoff_30d) & (pl.col("event_type") == "kyc_earned"))
        .group_by("client_id")
        .agg(pl.col("amount").sum().alias("a_earned_30d"))
    )
    earned_map = {r["client_id"]: r["a_earned_30d"] for r in earned_recent.iter_rows(named=True)}

    clients_out = []
    for row in _clients.iter_rows(named=True):
        cid   = row["client_id"]
        ctype = row["type"]
        is_issuer = (ctype == "FULL_KYC")
        ba = round(bal_a.get(cid, 0.0), 1)
        bb = round(bal_b.get(cid, 0.0), 1)
        a_earned = earned_map.get(cid, 0.0)
        b_spent = spent_map.get(cid, 0.0)
        runway = round(bb / (b_spent / 30 + 0.001), 1) if not is_issuer else 9999
        clients_out.append({
            "client_id":    cid,
            "name":         row["name"],
            "type":         ctype,
            "bal_a":        ba,
            "bal_b":        bb,
            "a_earned_30d": round(a_earned, 1),
            "b_spent_30d":  round(b_spent, 1),
            "runway_days":  runway,
        })

    # Monthly Credit A→B conversions
    monthly_conv = (
        _credit_ledger.filter(pl.col("event_type") == "convert_from_A")
        .with_columns(pl.col("date").str.slice(0, 7).alias("month"))
        .group_by("month")
        .agg(pl.sum("amount").alias("credit_b_converted"))
        .sort("month")
    )

    # Monthly Credit A earned
    monthly_a = (
        _credit_ledger.filter((pl.col("credit_type")=="A") & (pl.col("amount")>0))
        .with_columns(pl.col("date").str.slice(0, 7).alias("month"))
        .group_by("month")
        .agg(pl.sum("amount").alias("credit_a"))
        .sort("month")
    )

    low_b = [c for c in clients_out if c["bal_b"] < 20 and c["type"] == "ZKP_ONLY"]

    return {
        "credit_summary": {
            "credit_a_total_minted": round(credit_a_minted, 0),
            "credit_a_converted": round(credit_a_converted, 0),
            "credit_a_retained": credit_a_retained,
            "credit_b_converted": round(credit_b_converted, 0),
            "credit_b_face_value": credit_b_face_value,
            "kyc_revenue_usd": kyc_revenue,
        },
        "clients":     clients_out,
        "low_balance_alerts": low_b,
        "monthly_credit_a": {
            "months":   monthly_a["month"].to_list(),
            "credit_a": monthly_a["credit_a"].to_list(),
        },
        "monthly_conversions": {
            "months":            monthly_conv["month"].to_list(),
            "credit_b_converted": monthly_conv["credit_b_converted"].to_list(),
        },
    }


# ── API: credits per client ──────────────────────────────────────────────
@app.get("/api/tokens/{client_id}")
def api_tokens_client(client_id: int):
    _load()
    events = (
        _credit_ledger
        .filter(pl.col("client_id") == client_id)
        .sort("date")
    )
    if events.is_empty():
        raise HTTPException(status_code=404, detail="Client not found")
    client = _clients.filter(pl.col("client_id") == client_id).row(0, named=True)
    return {
        "client_id": client_id,
        "name":      client["name"],
        "type":      client["type"],
        "events":    events.select(["date","credit_type","event_type","amount","balance_after"]).to_dicts(),
        "dates":     events["date"].to_list(),
        "balance":   events["balance_after"].to_list(),
    }


# ── API: verifications ────────────────────────────────────────────────────────
@app.get("/api/verifications")
def api_verifications():
    _load()

    has_split = "initial_kyc" in _verifications.schema

    # Monthly totals platform-wide
    agg_cols = [
        pl.sum("full_kyc").alias("full_kyc"),
        pl.sum("reduced").alias("reduced"),
        pl.sum("failed").alias("failed"),
        pl.sum("total").alias("total"),
    ]
    if has_split:
        agg_cols += [
            pl.sum("initial_kyc").alias("initial_kyc"),
            pl.sum("rekyc").alias("rekyc"),
        ]

    monthly = (
        _verifications
        .with_columns(pl.col("date").str.slice(0, 7).alias("month"))
        .group_by("month")
        .agg(agg_cols)
        .sort("month")
    )

    # Per-type totals (FULL_KYC vs ZKP_ONLY)
    with_type = _verifications.join(
        _clients.select(["client_id","type","name"]), on="client_id"
    )
    by_type = (
        with_type.group_by("type")
        .agg(pl.sum("total").alias("total"))
    )

    # Per-client totals for table
    per_client_agg = [
        pl.sum("full_kyc").alias("full_kyc"),
        pl.sum("reduced").alias("reduced"),
        pl.sum("total").alias("total"),
        pl.sum("failed").alias("failed"),
    ]
    if has_split:
        per_client_agg += [
            pl.sum("initial_kyc").alias("initial_kyc"),
            pl.sum("rekyc").alias("rekyc"),
        ]
    per_client = (
        _verifications
        .group_by("client_id")
        .agg(per_client_agg)
        .join(_clients.select(["client_id","name","type"]), on="client_id")
        .with_columns(
            (pl.col("failed") / (pl.col("total") + 1) * 100).round(1).alias("fail_rate")
        )
        .sort("total", descending=True)
    )

    type_map = {r["type"]: r["total"] for r in by_type.iter_rows(named=True)}

    result = {
        "has_split": has_split,
        "monthly": {
            "months":   monthly["month"].to_list(),
            "full_kyc": monthly["full_kyc"].to_list(),
            "reduced":  monthly["reduced"].to_list(),
            "failed":   monthly["failed"].to_list(),
            "total":    monthly["total"].to_list(),
        },
        "by_type": type_map,
        "per_client": per_client.to_dicts(),
    }
    if has_split:
        result["monthly"]["initial_kyc"] = monthly["initial_kyc"].to_list()
        result["monthly"]["rekyc"] = monthly["rekyc"].to_list()
    return result


# ── API: rings ────────────────────────────────────────────────────────────────
@app.get("/api/rings")
def api_rings():
    _load()
    ring_ids = _rings["ring_id"].unique().sort().to_list()

    series: dict[str, dict] = {}
    for rid in ring_ids:
        rows = _rings.filter(pl.col("ring_id") == rid).sort("date")
        label = rows["ring_label"][0]
        series[rid] = {
            "label":  label,
            "dates":  rows["date"].to_list(),
            "counts": rows["member_count"].to_list(),
        }

    # Latest snapshot
    latest = (
        _rings.sort("date")
        .group_by("ring_id")
        .agg(
            pl.last("ring_label").alias("label"),
            pl.last("member_count").alias("count"),
            pl.first("member_count").alias("first_count"),
        )
        .with_columns(
            ((pl.col("count") - pl.col("first_count")) / pl.col("first_count") * 100)
            .round(1).alias("growth_pct")
        )
        .sort("ring_id")
    )

    return {
        "series": series,
        "latest": latest.to_dicts(),
    }


# ── API: clients ──────────────────────────────────────────────────────────────
@app.get("/api/clients")
def api_clients():
    _load()

    last_bal = (
        _credit_ledger.sort("date")
        .group_by(["client_id","credit_type"])
        .agg(pl.last("balance_after").alias("balance"))
    )
    # Split balance into A and B for every client
    bal_a_map = {r["client_id"]: r["balance"] for r in last_bal.filter(pl.col("credit_type")=="A").iter_rows(named=True)}
    bal_b_map = {r["client_id"]: r["balance"] for r in last_bal.filter(pl.col("credit_type")=="B").iter_rows(named=True)}

    last_activity = (
        _verifications.sort("date")
        .group_by("client_id")
        .agg(pl.last("date").alias("last_active"))
    )
    total_verif = (
        _verifications.group_by("client_id")
        .agg(pl.sum("total").alias("total_verifications"))
    )

    rows_out = []
    for row in _clients.iter_rows(named=True):
        cid = row["client_id"]
        rows_out.append({
            "client_id": cid,
            "balance_a": round(bal_a_map.get(cid, 0.0), 1),
            "balance_b": round(bal_b_map.get(cid, 0.0), 1),
        })
    bal_df = pl.DataFrame(rows_out)

    result = (
        _clients
        .join(bal_df, on="client_id", how="left")
        .join(last_activity, on="client_id", how="left")
        .join(total_verif, on="client_id", how="left")
        .with_columns([
            pl.col("balance_a").fill_null(0),
            pl.col("balance_b").fill_null(0),
            pl.col("total_verifications").fill_null(0),
            pl.col("last_active").fill_null("never"),
        ])
        .sort("total_verifications", descending=True)
    )

    return {"clients": result.to_dicts()}


@app.get("/api/clients/{client_id}")
def api_client_detail(client_id: int):
    _load()
    c = _clients.filter(pl.col("client_id") == client_id)
    if c.is_empty():
        raise HTTPException(status_code=404, detail="Client not found")
    client = c.row(0, named=True)

    # Verification history (monthly)
    monthly = (
        _verifications.filter(pl.col("client_id") == client_id)
        .with_columns(pl.col("date").str.slice(0, 7).alias("month"))
        .group_by("month")
        .agg(
            pl.sum("full_kyc").alias("full_kyc"),
            pl.sum("reduced").alias("reduced"),
            pl.sum("total").alias("total"),
        )
        .sort("month")
    )

    # Credit history
    credit_events = (
        _credit_ledger.filter(pl.col("client_id") == client_id)
        .sort("date")
    )

    return {
        "client": client,
        "monthly_verifications": monthly.to_dicts(),
        "credit_events": credit_events.select(["date","credit_type","event_type","amount","balance_after"]).to_dicts(),
    }


# ── API: anomalies ────────────────────────────────────────────────────────────
@app.get("/api/anomalies")
def api_anomalies():
    _load()

    with_client = (
        _anomalies
        .join(_clients.select(["client_id","name","type"]), on="client_id")
        .sort("date", descending=True)
    )

    # Counts by type
    by_type = (
        _anomalies.group_by("anomaly_type")
        .agg(pl.len().alias("count"))
        .sort("count", descending=True)
    )

    # Counts by severity
    by_severity = (
        _anomalies.group_by("severity")
        .agg(pl.len().alias("count"))
    )

    # Monthly count
    monthly = (
        _anomalies
        .with_columns(pl.col("date").str.slice(0, 7).alias("month"))
        .group_by("month")
        .agg(pl.len().alias("count"))
        .sort("month")
    )

    return {
        "events": with_client.head(200).to_dicts(),
        "by_type": by_type.to_dicts(),
        "by_severity": by_severity.to_dicts(),
        "monthly": {
            "months": monthly["month"].to_list(),
            "counts": monthly["count"].to_list(),
        },
    }


# ── API: insights (analytics) ─────────────────────────────────────────────────

def _ser(v):
    """JSON-safe serialiser for numpy / polars types."""
    if isinstance(v, (np.integer,)):       return int(v)
    if isinstance(v, (np.floating,)):      return float(v)
    if isinstance(v, (np.bool_,)):         return bool(v)
    return v

def _df_to_dicts(df: pl.DataFrame) -> list:
    rows = df.to_dicts()
    return [{k: _ser(val) for k, val in r.items()} for r in rows]


@app.get("/api/insights/clients")
def api_insights_clients():
    _load()
    _load_analytics()
    joined = (
        _client_scores
        .join(_clients.select(["client_id","name","type","sector","country"]), on="client_id")
        .join(_runway_forecast.select(["client_id","runway_days","burn_rate",
                                       "projected_depletion","current_balance"]), on="client_id")
        .sort("churn_risk", descending=True)
    )
    return {"clients": _df_to_dicts(joined)}


@app.get("/api/insights/forecast")
def api_insights_forecast():
    _load_analytics()
    rows = _df_to_dicts(_revenue_forecast)
    actual    = [r for r in rows if not r["is_forecast"]]
    forecast  = [r for r in rows if r["is_forecast"]]
    return {"actual": actual, "forecast": forecast}


@app.get("/api/insights/anomalies-ml")
def api_insights_anomalies_ml():
    _load()
    _load_analytics()
    with_client = (
        _anomalies_ml
        .join(_clients.select(["client_id","name","type"]), on="client_id")
        .sort("date", descending=True)
    )
    by_type = (
        _anomalies_ml.group_by("anomaly_type")
        .agg(pl.len().alias("count"))
        .sort("count", descending=True)
    )
    by_sev = (
        _anomalies_ml.group_by("severity")
        .agg(pl.len().alias("count"))
    )
    return {
        "events":      _df_to_dicts(with_client.head(300)),
        "by_type":     _df_to_dicts(by_type),
        "by_severity": _df_to_dicts(by_sev),
        "total":       len(_anomalies_ml),
    }


@app.get("/api/insights/rings")
def api_insights_rings():
    _load_analytics()
    return {"curves": _df_to_dicts(_ring_curves)}


@app.get("/api/insights/cohorts")
def api_insights_cohorts():
    _load_analytics()
    cohorts  = sorted(_cohort_analysis["cohort"].unique().to_list())
    months   = sorted(_cohort_analysis["month"].unique().to_list())
    # build matrix [cohort][month] = vol_per_client
    matrix = {}
    for r in _cohort_analysis.iter_rows(named=True):
        matrix.setdefault(r["cohort"], {})[r["month"]] = r["vol_per_client"]
    # fill None for missing cells
    grid = []
    for c in cohorts:
        grid.append([matrix.get(c, {}).get(m) for m in months])
    cohort_sizes = (
        _cohort_analysis
        .group_by("cohort")
        .agg(pl.col("cohort_size").first())
        .sort("cohort")
        .to_dicts()
    )
    return {"cohorts": cohorts, "months": months, "grid": grid, "sizes": cohort_sizes}


@app.get("/api/insights/load")
def api_insights_load():
    _load_analytics()
    rows = _df_to_dicts(_load_forecast)
    hist     = [r for r in rows if not r["is_forecast"]]
    forecast = [r for r in rows if r["is_forecast"]]
    return {"historical": hist, "forecast": forecast}


@app.get("/api/insights/elasticity")
def api_insights_elasticity():
    _load_analytics()
    return {"metrics": _df_to_dicts(_elasticity)}


@app.get("/api/insights")
def api_insights_summary():
    _load()
    _load_analytics()
    # high-risk clients (churn > 50%)
    at_risk = (
        _client_scores
        .filter(pl.col("churn_risk") > 0.5)
        .join(_clients.select(["client_id","name","type"]), on="client_id")
        .sort("churn_risk", descending=True)
        .head(10)
    )
    avg_churn  = float(_client_scores["churn_risk"].mean())
    avg_trust  = float(_client_scores["trust_score"].mean())
    ml_anom    = len(_anomalies_ml)
    ring_stats = _ring_curves.select(["ring_label","saturation_pct"]).to_dicts()

    return {
        "avg_churn_risk":       round(avg_churn, 4),
        "avg_trust_score":      round(avg_trust, 1),
        "ml_anomalies_detected":ml_anom,
        "at_risk_clients":      _df_to_dicts(at_risk),
        "ring_saturation":      ring_stats,
    }


# ── GDPR data retention ───────────────────────────────────────────────────────

@app.get("/api/gdpr/stats")
def gdpr_stats():
    _load()
    from gdpr_purge import EU_EEA_COUNTRIES

    today     = datetime.now().date()
    cutoff    = str(today - timedelta(days=365))
    total     = int(_sauron_users.height)
    anonymized = int(_sauron_users.filter(pl.col("is_anonymized")).height)

    eu_mask       = pl.col("country").is_in(list(EU_EEA_COUNTRIES)) \
                    if "country" in _sauron_users.schema \
                    else pl.lit(True)
    eu_eea_total  = int(_sauron_users.filter(eu_mask).height)
    non_eu_total  = total - eu_eea_total

    eligible = int(
        _sauron_users.filter(
            eu_mask &
            (pl.col("last_auth_date") < cutoff) &
            (pl.col("is_anonymized") == False)
        ).height
    )
    active = eu_eea_total - anonymized - eligible

    # Last purge info
    last_run_date   = None
    last_run_purged = 0
    if _gdpr_log is not None and _gdpr_log.height > 0 and "run_date" in _gdpr_log.schema:
        last_row        = _gdpr_log.sort("run_date").tail(1)
        last_run_date   = last_row["run_date"][0]
        last_run_purged = int(last_row["newly_purged"][0])

    # Monthly history
    history: list[dict] = []
    if _gdpr_log is not None and _gdpr_log.height > 0 and "run_date" in _gdpr_log.schema:
        monthly = (
            _gdpr_log
            .with_columns(pl.col("run_date").str.slice(0, 7).alias("month"))
            .group_by("month")
            .agg(pl.sum("newly_purged").alias("purged"))
            .sort("month")
        )
        history = [{"month": r["month"], "purged": r["purged"]}
                   for r in monthly.to_dicts()]

    run_log: list[dict] = []
    if _gdpr_log is not None and _gdpr_log.height > 0 and "run_date" in _gdpr_log.schema:
        run_log = _gdpr_log.sort("run_date", descending=True).to_dicts()

    return {
        "total_users":      total,
        "eu_eea_scope":     eu_eea_total,
        "non_eu_total":     non_eu_total,
        "active_users":     active,
        "anonymized_total": anonymized,
        "pending_purge":    eligible,
        "retention_days":   365,
        "cutoff_date":      cutoff,
        "last_run_date":    last_run_date,
        "last_run_purged":  last_run_purged,
        "monthly_history":  history,
        "run_log":          run_log,
    }


@app.post("/api/gdpr/purge")
async def gdpr_manual_purge():
    """Manual trigger — runs purge immediately and returns summary."""
    try:
        result = _run_gdpr_purge()
        # Reload in-memory state so API reflects new state
        global _sauron_users, _gdpr_log
        _sauron_users = pl.read_parquet(DATA / "sauron_users.parquet")
        _gdpr_log     = pl.read_parquet(DATA / "gdpr_log.parquet") if (DATA / "gdpr_log.parquet").exists() else pl.DataFrame()
        return result
    except Exception as exc:
        raise HTTPException(500, f"Purge failed: {exc}")


# ── Pipeline stats proxy ──────────────────────────────────────────────────────

@app.get("/api/pipeline-stats")
async def pipeline_stats():
    try:
        async with httpx.AsyncClient(timeout=3.0) as client:
            resp = await client.get(f"{INGEST_URL}/ingest/stats")
            return resp.json()
    except Exception as exc:
        raise HTTPException(503, f"Ingest server unavailable: {exc}")


# ── Live fraud feed (proxy from ingest SSE) ───────────────────────────────────

@app.get("/api/fraud-stream")
async def fraud_stream(request: Request):
    """
    Proxy the ingest server's SSE stream to dashboard clients.
    If the ingest server is not running, the stream ends gracefully.
    """
    async def generator() -> AsyncIterator[str]:
        try:
            async with httpx.AsyncClient(timeout=None) as client:
                async with client.stream("GET", f"{INGEST_URL}/ingest/stream") as resp:
                    async for line in resp.aiter_lines():
                        if await request.is_disconnected():
                            break
                        if line:
                            yield f"{line}\n"
                        else:
                            yield "\n"
        except Exception as exc:
            yield f"data: {json.dumps({'error': str(exc)})}\n\n"

    return StreamingResponse(generator(), media_type="text/event-stream")


# ══════════════════════════════════════════════════════════════════════════════
#  Company Analytics endpoints (merged from analytics-dashboard)
# ══════════════════════════════════════════════════════════════════════════════

# ── Sauron backend proxy (for analytics JSON stored in Rust DB) ──────────────
def _fetch_sauron(data_type: str, company_id: int) -> dict:
    """Fetch analytics data from the Sauron Rust backend."""
    url = f"{SAURON_URL}/data/{data_type}/{company_id}"
    try:
        req = UrlRequest(url, method="GET")
        with urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode())
    except UrlHTTPError as e:
        if e.code == 404:
            raise HTTPException(404, f"No {data_type} data for company {company_id}")
        raise HTTPException(502, f"Sauron backend error: {e.code}")
    except Exception as e:
        raise HTTPException(502, f"Cannot reach Sauron backend: {e}")


# ── CSV data cached at first load ─────────────────────────────────────────────
_companies_cache  : list[dict] | None = None
_trends_cache     : list[dict] | None = None
_personas_cache   : list[dict] | None = None


def _load_companies() -> list[dict]:
    global _companies_cache
    if _companies_cache is None:
        path = os.path.join(DATA_DIR, "companies.csv")
        if not os.path.exists(path):
            return []
        with open(path, encoding="utf-8") as f:
            _companies_cache = list(csv.DictReader(f))
    return _companies_cache


def _load_trends() -> list[dict]:
    global _trends_cache
    if _trends_cache is None:
        path = os.path.join(DATA_DIR, "company_trends.csv")
        if not os.path.exists(path):
            return []
        rows = []
        with open(path, encoding="utf-8") as f:
            for r in csv.DictReader(f):
                r["month"]               = int(r["month"])
                r["trend_index"]         = float(r["trend_index"])
                r["estimated_customers"] = int(r["estimated_customers"])
                rows.append(r)
        _trends_cache = rows
    return _trends_cache


def _load_personas() -> list[dict]:
    global _personas_cache
    if _personas_cache is None:
        path = os.path.join(DATA_DIR, "personas.csv")
        if not os.path.exists(path):
            return []
        with open(path, encoding="utf-8") as f:
            _personas_cache = list(csv.DictReader(f))
    return _personas_cache


def _persona_summary(rows: list[dict]) -> dict:
    categories = ["food_living", "tech", "lifestyle", "travel", "investment"]
    avg_spend  = {}
    for cat in categories:
        vals = [float(r[f"{cat}_usd"]) for r in rows if r.get(f"{cat}_usd")]
        avg_spend[cat] = round(sum(vals) / len(vals), 2) if vals else 0
    avg_net_worth = round(sum(float(r["net_worth_usd"]) for r in rows) / len(rows), 2) if rows else 0
    avg_income    = round(sum(float(r["monthly_income_usd"]) for r in rows) / len(rows), 2) if rows else 0
    return {
        "total":                 len(rows),
        "by_country":            dict(Counter(r["country"]           for r in rows)),
        "by_tier":               dict(Counter(r["wealth_tier"]        for r in rows)),
        "by_generation":         dict(Counter(r["generation"]         for r in rows)),
        "by_frequency":          dict(Counter(r["internet_frequency"] for r in rows)),
        "avg_monthly_spend_usd": avg_spend,
        "avg_net_worth_usd":     avg_net_worth,
        "avg_monthly_income_usd": avg_income,
    }


# ── Analytics HTML pages ──────────────────────────────────────────────────────
@app.get("/forecast", response_class=HTMLResponse)
def page_forecast():
    return _page("forecast.html")

@app.get("/fraud", response_class=HTMLResponse)
def page_fraud():
    return _page("fraud.html")


# ── Analytics Data APIs ──────────────────────────────────────────────────────
@app.get("/api/companies")
async def get_companies_csv():
    return _load_companies()

@app.get("/api/trends")
async def get_trends_csv():
    return _load_trends()

@app.get("/api/personas/summary")
async def get_personas_summary():
    return _persona_summary(_load_personas())

@app.get("/api/personas/by_category/{category}")
async def get_personas_by_category(category: str):
    if category not in VALID_CATEGORIES:
        raise HTTPException(400, f"Invalid category. Must be one of: {sorted(VALID_CATEGORIES)}")
    cats = list(VALID_CATEGORIES)
    def primary_cat(r: dict) -> str:
        return max(cats, key=lambda c: float(r.get(f"{c}_usd", 0)))
    filtered = [r for r in _load_personas() if primary_cat(r) == category]
    if not filtered:
        raise HTTPException(404, f"No personas found for category '{category}'")
    summary = _persona_summary(filtered)
    summary["category"] = category
    return summary

@app.get("/api/forecast/{company_id}")
async def get_forecast(company_id: int):
    if company_id <= 0:
        raise HTTPException(400, "company_id must be a positive integer")
    return _fetch_sauron("forecast", company_id)

@app.get("/api/fraud/summary/{company_id}")
async def get_fraud_summary(company_id: int):
    if company_id <= 0:
        raise HTTPException(400, "company_id must be a positive integer")
    return _fetch_sauron("fraud_summary", company_id)

@app.get("/api/fraud/recent/{company_id}")
async def get_fraud_recent(company_id: int):
    if company_id <= 0:
        raise HTTPException(400, "company_id must be a positive integer")
    return _fetch_sauron("fraud_recent", company_id)

@app.get("/api/stats/{company_id}")
async def get_company_stats(company_id: int):
    if company_id <= 0:
        raise HTTPException(400, "company_id must be a positive integer")
    return _fetch_sauron("stats", company_id)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=8002, reload=True)
