# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x07trustid\"\xad\x01\n\x05\x45vent\x12\x12\n\ncompany_id\x18\x01 \x01(\r\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12(\n\x0b\x61\x63tion_type\x18\x03 \x01(\x0e\x32\x13.trustid.ActionType\x12\x12\n\namount_usd\x18\x04 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x12\x16\n\x0e\x63redit_balance\x18\x06 \x01(\x02\x12\x13\n\x0b\x61uth_failed\x18\x07 \x01(\x08\"\xcd\x01\n\x08\x44\x65\x63ision\x12\x12\n\ncompany_id\x18\x01 \x01(\r\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12&\n\nrisk_level\x18\x04 \x01(\x0e\x32\x12.trustid.RiskLevel\x12\x10\n\x08is_fraud\x18\x05 \x01(\x08\x12\x13\n\x0b\x66raud_score\x18\x06 \x01(\x02\x12\x0f\n\x07z_score\x18\x07 \x01(\x02\x12\x0e\n\x06reason\x18\x08 \x01(\t\x12\x16\n\x0e\x63redit_balance\x18\t \x01(\x02\",\n\nEventBatch\x12\x1e\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x0e.trustid.Event*g\n\nActionType\x12\x12\n\x0e\x41\x43TION_UNKNOWN\x10\x00\x12\x16\n\x12\x41\x43TION_TRANSACTION\x10\x01\x12\x18\n\x14\x41\x43TION_LOGIN_ATTEMPT\x10\x02\x12\x13\n\x0f\x41\x43TION_API_CALL\x10\x03*:\n\tRiskLevel\x12\r\n\tRISK_PASS\x10\x00\x12\x0e\n\nRISK_WATCH\x10\x01\x12\x0e\n\nRISK_BLOCK\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONTYPE']._serialized_start=455
  _globals['_ACTIONTYPE']._serialized_end=558
  _globals['_RISKLEVEL']._serialized_start=560
  _globals['_RISKLEVEL']._serialized_end=618
  _globals['_EVENT']._serialized_start=26
  _globals['_EVENT']._serialized_end=199
  _globals['_DECISION']._serialized_start=202
  _globals['_DECISION']._serialized_end=407
  _globals['_EVENTBATCH']._serialized_start=409
  _globals['_EVENTBATCH']._serialized_end=453
# @@protoc_insertion_point(module_scope)
