"""
ingest/receiver.py
==================
FastAPI server that accepts protobuf-encoded events from company hosts.

Protocol
--------
POST /ingest/event
  Content-Type: application/x-protobuf
  Body: serialized Event (single) or EventBatch

POST /ingest/batch
  Content-Type: application/x-protobuf
  Body: serialized EventBatch

GET /ingest/stream
  Server-Sent Events feed — dashboard subscribes here to receive real-time
  Decision notifications without polling.

GET /ingest/health
  Returns 200 + {"status": "ok"}.

Delta decoding
--------------
The server maintains per-(company_id, user_id) last-seen state.
Any numeric field with its zero/sentinel value is filled from that state,
so companies can send only changed fields over the wire.

Thread safety
-------------
_state and the SSE queue are accessed only in the async event loop; no locks
needed as long as we stay on one FastAPI worker (single process).
"""

import asyncio
import collections
import json
import os
import sys
import time
from typing import AsyncIterator

import numpy as np
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import StreamingResponse
from starlette.responses import Response

# ── Proto import (generated by grpc_tools.protoc) ────────────────────────
sys.path.insert(0, os.path.dirname(__file__))
import events_pb2 as pb

# ── Local modules ─────────────────────────────────────────────────────────
from risk import RiskEngine
from notify import NotificationRouter

# ── Constants ─────────────────────────────────────────────────────────────
ROOT      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_DIR = os.path.join(ROOT, "ml", "fraud")
STATS_DIR = os.path.join(ROOT, "ml", "stats")

# ── App ───────────────────────────────────────────────────────────────────
app = FastAPI(title="TrustID Ingest", version="1.0.0")

# Lazy-initialised singletons
_risk: RiskEngine | None = None
_notify: NotificationRouter | None = None

# Per-(company_id, user_id) last known state for delta decoding.
# Capped at 500k entries (10k personas × 50 companies) via OrderedDict LRU
# to prevent unbounded memory growth under sustained load.
_STATE_CAP = 500_000
_state: collections.OrderedDict = collections.OrderedDict()

# ── Startup ───────────────────────────────────────────────────────────────

@app.on_event("startup")
async def _startup():
    global _risk, _notify
    _risk   = RiskEngine(MODEL_DIR, STATS_DIR)
    _notify = NotificationRouter()


# ── Delta decoding ────────────────────────────────────────────────────────

def _apply_delta(event: pb.Event) -> dict:
    """
    Merge incoming protobuf Event with stored per-(company, user) state.
    Returns a plain dict with all fields resolved.
    """
    key = (event.company_id, event.user_id)
    prev = _state.get(key, {})

    amount     = event.amount_usd   if event.amount_usd   != 0.0  else prev.get("amount_usd", 0.0)
    balance    = event.credit_balance if event.credit_balance != -1.0 else prev.get("credit_balance", -1.0)
    ts_ms      = event.timestamp_ms if event.timestamp_ms != 0    else int(time.time() * 1000)
    auth_failed = event.auth_failed

    resolved = {
        "company_id":    event.company_id,
        "user_id":       event.user_id,
        "action_type":   event.action_type,
        "amount_usd":    amount,
        "credit_balance": balance,
        "timestamp_ms":  ts_ms,
        "auth_failed":   auth_failed,
    }
    # LRU update: move key to end (most-recently-used), evict oldest if over cap
    _state[key] = resolved
    _state.move_to_end(key)
    if len(_state) > _STATE_CAP:
        _state.popitem(last=False)  # evict least-recently-used
    return resolved


# ── Processing ────────────────────────────────────────────────────────────

async def _process_event(raw: dict) -> dict:
    """
    Run risk checks and build a Decision dict.
    score() is <1 ms once warmed up — calling it directly avoids thread-pool
    overhead (queue, wake, marshal) which exceeds the compute time itself.
    """
    decision = _risk.score(raw)

    # Push to SSE queue
    await _notify.broadcast(decision)

    # Trigger webhook if WATCH or BLOCK
    if decision["risk_level"] in ("WATCH", "BLOCK"):
        asyncio.create_task(_notify.send_webhook(raw["company_id"], decision))

    return decision


def _decision_to_proto(d: dict) -> pb.Decision:
    level_map = {"PASS": pb.RISK_PASS, "WATCH": pb.RISK_WATCH, "BLOCK": pb.RISK_BLOCK}
    return pb.Decision(
        company_id    = d["company_id"],
        user_id       = d["user_id"],
        timestamp_ms  = d["timestamp_ms"],
        risk_level    = level_map.get(d["risk_level"], pb.RISK_PASS),
        is_fraud      = d["is_fraud"],
        fraud_score   = d["fraud_score"],
        z_score       = d["z_score"],
        reason        = d["reason"],
        credit_balance = d.get("credit_balance", -1.0),
    )


# ── Routes ────────────────────────────────────────────────────────────────

@app.get("/ingest/health")
async def health():
    return {"status": "ok", "models_loaded": _risk.n_models if _risk else 0}


@app.post("/ingest/event")
async def ingest_event(request: Request):
    body = await request.body()
    if not body:
        raise HTTPException(400, "Empty body")
    try:
        event = pb.Event()
        event.ParseFromString(body)
    except Exception as exc:
        raise HTTPException(400, f"Protobuf parse error: {exc}")

    if not event.company_id or not event.user_id:
        raise HTTPException(400, "company_id and user_id are required")

    resolved  = _apply_delta(event)
    decision  = await _process_event(resolved)
    proto_out = _decision_to_proto(decision)

    return Response(
        content      = proto_out.SerializeToString(),
        media_type   = "application/x-protobuf",
        status_code  = 200,
    )


@app.post("/ingest/batch")
async def ingest_batch(request: Request):
    body = await request.body()
    if not body:
        raise HTTPException(400, "Empty body")
    try:
        batch = pb.EventBatch()
        batch.ParseFromString(body)
    except Exception as exc:
        raise HTTPException(400, f"Protobuf parse error: {exc}")

    if not batch.events:
        raise HTTPException(400, "Empty batch")

    decisions = []
    for event in batch.events:
        if not event.company_id or not event.user_id:
            continue
        resolved = _apply_delta(event)
        decision = await _process_event(resolved)
        decisions.append(_decision_to_proto(decision))

    # Return a batch of decisions — wrap in a simple repeated field via
    # EventBatch (reuse the wrapper; real field would be DecisionBatch but
    # keeping proto simple for now)
    out = pb.EventBatch()  # placeholder; clients iterate the same way
    return Response(
        content    = json.dumps([{
            "company_id": d.company_id,
            "user_id":    d.user_id,
            "risk_level": ["PASS","WATCH","BLOCK"][d.risk_level],
            "is_fraud":   d.is_fraud,
            "fraud_score": round(d.fraud_score, 4),
            "z_score":    round(d.z_score, 3),
            "reason":     d.reason,
        } for d in decisions]),
        media_type = "application/json",
    )


# ── SSE stream ────────────────────────────────────────────────────────────

@app.get("/ingest/stream")
async def sse_stream(request: Request):
    """
    Server-Sent Events endpoint.  Dashboard connects here and receives
    real-time Decision notifications for WATCH and BLOCK events.
    """
    queue: asyncio.Queue = asyncio.Queue(maxsize=512)
    _notify.subscribe(queue)

    async def generator() -> AsyncIterator[str]:
        try:
            while True:
                if await request.is_disconnected():
                    break
                try:
                    msg = await asyncio.wait_for(queue.get(), timeout=15.0)
                    yield f"data: {json.dumps(msg)}\n\n"
                except asyncio.TimeoutError:
                    yield ": keepalive\n\n"
        finally:
            _notify.unsubscribe(queue)

    return StreamingResponse(generator(), media_type="text/event-stream")


# ── Entry point ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("receiver:app", host="0.0.0.0", port=8010, reload=False)
