/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentDelegationRegistry__factory } from "./AgentDelegationRegistry__factory";
export { RevocationRegistry__factory } from "./RevocationRegistry__factory";
