/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentDelegationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "DELEGATOR_ROLE"
      | "activeDelegations"
      | "getDelegation"
      | "getRoleAdmin"
      | "grantDelegator"
      | "grantRole"
      | "hasRole"
      | "isDelegationActive"
      | "registerDelegation"
      | "renounceRole"
      | "revokeDelegation"
      | "revokeDelegator"
      | "revokeRole"
      | "supportsInterface"
      | "totalDelegations"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DelegationExpired"
      | "DelegationRegistered"
      | "DelegationRevoked"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DELEGATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeDelegations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDelegation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantDelegator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDelegationActive",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDelegation",
    values: [BytesLike, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegation",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDelegations",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DELEGATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeDelegations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantDelegator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDelegationActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDelegations",
    data: BytesLike
  ): Result;
}

export namespace DelegationExpiredEvent {
  export type InputTuple = [agentChecksum: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [agentChecksum: string, timestamp: bigint];
  export interface OutputObject {
    agentChecksum: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DelegationRegisteredEvent {
  export type InputTuple = [
    agentChecksum: BytesLike,
    parentChecksum: BytesLike,
    registeredBy: AddressLike,
    expiresAt: BigNumberish,
    scope: string
  ];
  export type OutputTuple = [
    agentChecksum: string,
    parentChecksum: string,
    registeredBy: string,
    expiresAt: bigint,
    scope: string
  ];
  export interface OutputObject {
    agentChecksum: string;
    parentChecksum: string;
    registeredBy: string;
    expiresAt: bigint;
    scope: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DelegationRevokedEvent {
  export type InputTuple = [
    agentChecksum: BytesLike,
    revokedBy: AddressLike,
    timestamp: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    agentChecksum: string,
    revokedBy: string,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    agentChecksum: string;
    revokedBy: string;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentDelegationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentDelegationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentDelegationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DELEGATOR_ROLE: TypedContractMethod<[], [string], "view">;

  activeDelegations: TypedContractMethod<[], [bigint], "view">;

  getDelegation: TypedContractMethod<
    [agentChecksum: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean, string] & {
        parentChecksum: string;
        registeredBy: string;
        createdAt: bigint;
        expiresAt: bigint;
        active: boolean;
        revoked: boolean;
        scope: string;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantDelegator: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isDelegationActive: TypedContractMethod<
    [agentChecksum: BytesLike],
    [boolean],
    "view"
  >;

  registerDelegation: TypedContractMethod<
    [
      agentChecksum: BytesLike,
      parentChecksum: BytesLike,
      expiresAt: BigNumberish,
      scope: string
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeDelegation: TypedContractMethod<
    [agentChecksum: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  revokeDelegator: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalDelegations: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DELEGATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeDelegations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDelegation"
  ): TypedContractMethod<
    [agentChecksum: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean, string] & {
        parentChecksum: string;
        registeredBy: string;
        createdAt: bigint;
        expiresAt: bigint;
        active: boolean;
        revoked: boolean;
        scope: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantDelegator"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDelegationActive"
  ): TypedContractMethod<[agentChecksum: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerDelegation"
  ): TypedContractMethod<
    [
      agentChecksum: BytesLike,
      parentChecksum: BytesLike,
      expiresAt: BigNumberish,
      scope: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDelegation"
  ): TypedContractMethod<
    [agentChecksum: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDelegator"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalDelegations"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DelegationExpired"
  ): TypedContractEvent<
    DelegationExpiredEvent.InputTuple,
    DelegationExpiredEvent.OutputTuple,
    DelegationExpiredEvent.OutputObject
  >;
  getEvent(
    key: "DelegationRegistered"
  ): TypedContractEvent<
    DelegationRegisteredEvent.InputTuple,
    DelegationRegisteredEvent.OutputTuple,
    DelegationRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DelegationRevoked"
  ): TypedContractEvent<
    DelegationRevokedEvent.InputTuple,
    DelegationRevokedEvent.OutputTuple,
    DelegationRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "DelegationExpired(bytes32,uint256)": TypedContractEvent<
      DelegationExpiredEvent.InputTuple,
      DelegationExpiredEvent.OutputTuple,
      DelegationExpiredEvent.OutputObject
    >;
    DelegationExpired: TypedContractEvent<
      DelegationExpiredEvent.InputTuple,
      DelegationExpiredEvent.OutputTuple,
      DelegationExpiredEvent.OutputObject
    >;

    "DelegationRegistered(bytes32,bytes32,address,uint256,string)": TypedContractEvent<
      DelegationRegisteredEvent.InputTuple,
      DelegationRegisteredEvent.OutputTuple,
      DelegationRegisteredEvent.OutputObject
    >;
    DelegationRegistered: TypedContractEvent<
      DelegationRegisteredEvent.InputTuple,
      DelegationRegisteredEvent.OutputTuple,
      DelegationRegisteredEvent.OutputObject
    >;

    "DelegationRevoked(bytes32,address,uint256,string)": TypedContractEvent<
      DelegationRevokedEvent.InputTuple,
      DelegationRevokedEvent.OutputTuple,
      DelegationRevokedEvent.OutputObject
    >;
    DelegationRevoked: TypedContractEvent<
      DelegationRevokedEvent.InputTuple,
      DelegationRevokedEvent.OutputTuple,
      DelegationRevokedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
