/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgentDelegationRegistry } from "./AgentDelegationRegistry";
export type { RevocationRegistry } from "./RevocationRegistry";
